import { MainLayout } from "@/components/MainLayout";
import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white dark:text-[#D1D5DB] dark:bg-[#030712]" >
        <div className="max-w-[1216px] mx-auto bg-white dark:text-[#D1D5DB] dark:bg-[#030712]">
          <MainLayout>{children}</MainLayout>
        </div>
      </body>
    </html>
  );
}
